name: Backdrop CMS Contrib Functional Tests

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        default: ''

jobs:
  simpletest:
    name: Run Simpletest
    runs-on: ubuntu-22.04
    steps:
      - name: Setup env
        run: |
          echo "REPO_NAME=${PWD##*/}" >> $GITHUB_ENV
          echo 'USE_PHP_V=8.2' >> $GITHUB_ENV

      - name: Install MariaDB
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 'mariadb-10.11'
          root-password: 'root'
          auto-start: true

      - name: Verify setup and create database
        run: |
          echo -e '[client]\nuser = root\npassword = root\nhost = 127.0.0.1' > ~/.my.cnf
          mysql -e 'SELECT version()\G'
          mysql -e 'CREATE DATABASE backdrop;'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.USE_PHP_V }}
          coverage: none
          tools: none

      - name: Checkout Backdrop core
        uses: actions/checkout@v4
        with:
          repository: backdrop/backdrop

      # @todo: figure out how to pull dependencies, if any, here.
      #- name: Checkout Dependencies
      #  if: ${{ inputs.dependencies != '' }}
      #  uses: actions/checkout@v4
      #  with:
      #    repository: backdrop-contrib/${{ inputs.dependencies }}
      #    path: modules/${{ inputs.dependencies }}

      - name: Setup Apache
        run: |
          sudo curl https://raw.githubusercontent.com/backdrop-ops/gha/refs/heads/main/.github/misc/default.conf --output /etc/apache2/sites-available/000-default.conf
          sudo sed -i -e "s?_PWD?$PWD?g" -e "s/_PHP_V/${{ env.USE_PHP_V }}/g" /etc/apache2/sites-available/000-default.conf
          sudo apt-get install libapache2-mod-fcgid
          sudo a2enmod rewrite proxy fcgid proxy_fcgi
          sudo chmod 751 /home/runner
          sudo systemctl start apache2.service
          sudo sed -i -e 's/user = www-data/user = runner/' /etc/php/${{ env.USE_PHP_V }}/fpm/pool.d/www.conf
          sudo sed -i -e 's/listen.owner = www-data/listen.owner = runner/' /etc/php/${{ env.USE_PHP_V }}/fpm/pool.d/www.conf
          sudo systemctl restart php${{ env.USE_PHP_V }}-fpm.service

      - name: Install Backdrop
        run: |
          curl https://raw.githubusercontent.com/backdrop-ops/gha/refs/heads/main/.github/misc/settings.local.php --output ./settings.local.php
          core/scripts/install.sh --db-url=mysql://root:root@127.0.0.1/backdrop

      - name: Run functional tests
        run: core/scripts/run-tests.sh --force --directory=modules/${{ env.REPO_NAME }} --verbose --color --concurrency=3 --cache 2>&1
